version: 2.0
jobs:
  "clang":
    docker:
      - image: ubuntu:16.04
        environment:
          CC: clang-6.0
          CXX: clang++-6.0
          CLANG_FORMAT: clang-format-6.0
    steps:
      - checkout
      - run: apt-get update -qq
      - run: >
          apt-get install -y --allow-unauthenticated
          build-essential
          cmake
          clang-6.0
          clang-format-6.0
      - run: cmake ./ -DDIRTY=1   
      - run: make
      - run: ./main


  "gcc":
    docker:
      - image: ubuntu:16.04
        environment:
          CC: gcc
          CXX: g++
          SHARED_LIBS: OFF
    steps:
      - checkout
      - run: apt-get update -qq
      - run: >
          apt-get install -y --allow-unauthenticated
          build-essential
          cmake
      - run: cmake ./ -DDIRTY=1   
      - run: make
      - run: ./main
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - "clang"
      - "gcc"
